# .github/workflows/release.yaml

on: 
  release:
    types: [created]

jobs:
  release-linux:
    name: release linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        project_path: "./cmd/test-binary"
        binary_name: "test-binary"
        goos: linux
        goarch: ${{ matrix.goarch }}
